// AUTO-GENERATED by gen-flags.mjs — do not edit by hand.
// Static imports of only the 48 flags this tournament needs, so Vite
// bundles just these (instead of the full flag-icons set) and they get hashed,
// long-cache asset URLs.
import f_mx from 'flag-icons/flags/4x3/mx.svg'
import f_za from 'flag-icons/flags/4x3/za.svg'
import f_kr from 'flag-icons/flags/4x3/kr.svg'
import f_cz from 'flag-icons/flags/4x3/cz.svg'
import f_ca from 'flag-icons/flags/4x3/ca.svg'
import f_ba from 'flag-icons/flags/4x3/ba.svg'
import f_qa from 'flag-icons/flags/4x3/qa.svg'
import f_ch from 'flag-icons/flags/4x3/ch.svg'
import f_br from 'flag-icons/flags/4x3/br.svg'
import f_ma from 'flag-icons/flags/4x3/ma.svg'
import f_ht from 'flag-icons/flags/4x3/ht.svg'
import f_gb_sct from 'flag-icons/flags/4x3/gb-sct.svg'
import f_us from 'flag-icons/flags/4x3/us.svg'
import f_py from 'flag-icons/flags/4x3/py.svg'
import f_au from 'flag-icons/flags/4x3/au.svg'
import f_tr from 'flag-icons/flags/4x3/tr.svg'
import f_de from 'flag-icons/flags/4x3/de.svg'
import f_cw from 'flag-icons/flags/4x3/cw.svg'
import f_ci from 'flag-icons/flags/4x3/ci.svg'
import f_ec from 'flag-icons/flags/4x3/ec.svg'
import f_nl from 'flag-icons/flags/4x3/nl.svg'
import f_jp from 'flag-icons/flags/4x3/jp.svg'
import f_se from 'flag-icons/flags/4x3/se.svg'
import f_tn from 'flag-icons/flags/4x3/tn.svg'
import f_be from 'flag-icons/flags/4x3/be.svg'
import f_eg from 'flag-icons/flags/4x3/eg.svg'
import f_ir from 'flag-icons/flags/4x3/ir.svg'
import f_nz from 'flag-icons/flags/4x3/nz.svg'
import f_es from 'flag-icons/flags/4x3/es.svg'
import f_cv from 'flag-icons/flags/4x3/cv.svg'
import f_sa from 'flag-icons/flags/4x3/sa.svg'
import f_uy from 'flag-icons/flags/4x3/uy.svg'
import f_fr from 'flag-icons/flags/4x3/fr.svg'
import f_sn from 'flag-icons/flags/4x3/sn.svg'
import f_iq from 'flag-icons/flags/4x3/iq.svg'
import f_no from 'flag-icons/flags/4x3/no.svg'
import f_ar from 'flag-icons/flags/4x3/ar.svg'
import f_dz from 'flag-icons/flags/4x3/dz.svg'
import f_at from 'flag-icons/flags/4x3/at.svg'
import f_jo from 'flag-icons/flags/4x3/jo.svg'
import f_pt from 'flag-icons/flags/4x3/pt.svg'
import f_cd from 'flag-icons/flags/4x3/cd.svg'
import f_uz from 'flag-icons/flags/4x3/uz.svg'
import f_co from 'flag-icons/flags/4x3/co.svg'
import f_gb_eng from 'flag-icons/flags/4x3/gb-eng.svg'
import f_hr from 'flag-icons/flags/4x3/hr.svg'
import f_gh from 'flag-icons/flags/4x3/gh.svg'
import f_pa from 'flag-icons/flags/4x3/pa.svg'

export const FLAG_URLS: Record<string, string> = {
  'mx': f_mx,
  'za': f_za,
  'kr': f_kr,
  'cz': f_cz,
  'ca': f_ca,
  'ba': f_ba,
  'qa': f_qa,
  'ch': f_ch,
  'br': f_br,
  'ma': f_ma,
  'ht': f_ht,
  'gb-sct': f_gb_sct,
  'us': f_us,
  'py': f_py,
  'au': f_au,
  'tr': f_tr,
  'de': f_de,
  'cw': f_cw,
  'ci': f_ci,
  'ec': f_ec,
  'nl': f_nl,
  'jp': f_jp,
  'se': f_se,
  'tn': f_tn,
  'be': f_be,
  'eg': f_eg,
  'ir': f_ir,
  'nz': f_nz,
  'es': f_es,
  'cv': f_cv,
  'sa': f_sa,
  'uy': f_uy,
  'fr': f_fr,
  'sn': f_sn,
  'iq': f_iq,
  'no': f_no,
  'ar': f_ar,
  'dz': f_dz,
  'at': f_at,
  'jo': f_jo,
  'pt': f_pt,
  'cd': f_cd,
  'uz': f_uz,
  'co': f_co,
  'gb-eng': f_gb_eng,
  'hr': f_hr,
  'gh': f_gh,
  'pa': f_pa,
}

/** Eagerly fetch every flag so the browser caches them before they're shown. */
export function preloadFlags(): void {
  if (typeof Image === 'undefined') return
  for (const url of Object.values(FLAG_URLS)) {
    new Image().src = url
  }
}
